### ISSUE TITLE
No itemProcessor after pulling roach php

### ISSUE THREAD

**Issue by iamkarsoft** [ksassnowski/roach-example-project#1]
I'm getting started with roach-php/laravel and using this project as a guideline. After installing the package. I can't seem to find ItemProcessor in the package. But it exist on in this example project. I would be grateful for more guidance.

**Comment by AkioSarkiz** [comment]
You can't find `RoachPHP\ItemPipeline\ItemInterface`?

**Comment by JD456976** [comment]
Just pulled it and everything is there.

**Comment by iamkarsoft** [comment]
That was months ago.
